export const PATH = {
    DASHBOARD: '/dashboard',
    PRODUCT: '/dashboard/product',
    PROFILE: '/dashboard/profile',
    KANBAN: '/dashboard/kanban',
    OVERVIEW: '/dashboard/overview',
    LOGIN: '/',
    SIGNIN: '/auth/signin',
    SIGNUP: '/auth/signup',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    NOT_FOUND: '/404',
    SERVER_ERROR: '/500',
    MAINTENANCE: '/maintenance',
    UNDER_CONSTRUCTION: '/under-construction',
    COMING_SOON: '/coming-soon',
    LOCK_SCREEN: '/lock-screen',
    CHAT: '/chat',
    MAIL: '/mail',
    CALENDAR: '/calendar',
}