export const PATH = {
  DASHBOARD: '/dashboard',
  PRODUCT: '/dashboard/product',
  PROFILE: '/dashboard/profile',
  KANBAN: '/dashboard/kanban',
  OVERVIEW: '/dashboard/overview',
  LOGIN: '/',
  SIGNIN: '/sign-in',
  SIGNUP: '/sign-up',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  NOT_FOUND: '/404',
  SERVER_ERROR: '/500',
  MAINTENANCE: '/maintenance',
  UNDER_CONSTRUCTION: '/under-construction',
  COMING_SOON: '/coming-soon',
  LOCK_SCREEN: '/lock-screen',
  CHAT: '/chat',
  MAIL: '/mail',
  CALENDAR: '/calendar'
};
